language: go
go:
  - "1.12.x"
  - "1.11.x"
  - "1.10.x"
jobs:
  include:
    - stage: install
      script:
        - "go mod download"
        - "go mod vendor"
    - stage: test
      script:
        - "go test -v -coverprofile=coverage.txt -covermode=atomic"
        - "bash <(curl -s https://codecov.io/bash)"
